# Intro to python variables


1] Create and assign string variables

In [185]:
city_name = "Nagpur"

In [186]:
print(f"City Name : {city_name}")

City Name : Nagpur


2] Create and assign integer variable

In [188]:
temperature = 25

In [189]:
print(f"temperature: {temperature}C")

temperature: 25C


3]Create and assign float variable

In [191]:
carbon_footprint = 500.75 #kg co2

In [192]:
print(f"Carbon footprint : {carbon_footprint} kg CO2")

Carbon footprint : 500.75 kg CO2


4] Create and assign boolean variables

In [194]:
is_sustainable = carbon_footprint < 400 

In [195]:
print(f"Is the city sustainable? {is_sustainable}")

Is the city sustainable? False


5] Crerte and assign list of variables

In [197]:
weekly_temperature = [25,24,34,29]

print(f"Weekly temp : {weekly_temperature}")

6]Create a dict

# To implement Control Structure

## is input variable
print("enter a varible")
b=input()
if b.isdigit():
    print("true")
else:
    print("false")

## calculator

print("Calculator")

def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    if b != 0:
        return a / b
    else:
        return "Error!"

def calculator():
    print("Welcome to the Python Calculator!")
    print("Select operation:")
    print("1. Addition (+)")
    print("2. Subtraction (-)")
    print("3. Multiplication (*)")
    print("4. Division (/)")

    while True:
        try:
            choice = input("\nEnter your choice (1/2/3/4) or 'q' to quit: ").strip()
            if choice.lower() == 'q':
                print("Exit")
                break

            if choice not in ['1', '2', '3', '4']:
                print("Invalid choice.")
                continue

            num1 = float(input("Enter the first number: "))
            num2 = float(input("Enter the second number: "))

            if choice == '1':
                print(f"The result is: {add(num1, num2)}")
            elif choice == '2':
                print(f"The result is: {subtract(num1, num2)}")
            elif choice == '3':
                print(f"The result is: {multiply(num1, num2)}")
            elif choice == '4':
                print(f"The result is: {divide(num1, num2)}")
            elif choice == '5':
                print(f"The result is: {power(num1, num2)}")

        except ValueError:
            print("Invalid input!")

if __name__ == "__main__":
    calculator()



In [203]:
climate_data = [
    {"city": "City A", "temperature": 25, "carbon_footprint": 500},
    {"city": "City B", "temperature": 30, "carbon_footprint": 350},
    {"city": "City C", "temperature": 22, "carbon_footprint": 600},
    {"city": "City D", "temperature": 15, "carbon_footprint": 200},
    {"city": "City E", "temperature": 28, "carbon_footprint": 450},
]

In [204]:
#filter city with high temp
high_temp = 26
high_temp_fliter = [city for city in climate_data if city ["temperature"] >  high_temp]
print("City with high temp")
for city in high_temp_fliter:
    print(f"{city['city']} + {city["temperature"]}C")

City with high temp
City B + 30C
City E + 28C


In [205]:
#find avg of carbon footprint
#calculate the average carbon footprint using loop
total_carbon_footprint=0
for city in climate_data:
  total_carbon_footprint+=city["carbon_footprint"]
average_carbon_footprint=total_carbon_footprint/len(climate_data)
print(f"Average carbon footprint:{average_carbon_footprint}")

Average carbon footprint:420.0


In [206]:
len(climate_data)

5

In [207]:
#fing city with highest carbon footprint
higest_footprint = max(climate_data,key=lambda city: city["carbon_footprint"])
print("city with highest carbon footage")
print(f"{higest_footprint['city']} - {higest_footprint['carbon_footprint']} kg CO2")


city with highest carbon footage
City C - 600 kg CO2


In [208]:
# write a function to filter the city are sustainable or not(400 ton co2)
def is_sustainable(city):
  return city["carbon_footprint"]<=400

sustainable_cities=[city for city in climate_data if is_sustainable(city)]
print("Sustainable cities:")
for city in sustainable_cities:
  print(f"{city['city']}-{city['carbon_footprint']} kg CO2")

Sustainable cities:
City B-350 kg CO2
City D-200 kg CO2


# Functions

In [210]:
def add(a,b): 
    c=a+b
    return c

In [211]:
add(3,4)

7

In [212]:
y = lambda x: x + 2
print(y(3))

5


In [213]:
# leap year or not
def is_leap_year(year):
  
    if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
        return True
    else:
        return False

# Input from the user
year = int(input("Enter a year: "))

# Check if it's a leap year
if is_leap_year(year):
    print(f"{year} is a leap year.")
else:
    print(f"{year} is not a leap year.")


Enter a year:  2004


2004 is a leap year.


# Series dataframe using pandas

In [215]:
import pandas as pd

In [216]:
import pandas as pd


data = {
    "Project": ["Solar Farm A", "Wind Turbine X", "Hydropower Y", "Solar Roof Z", "Geothermal Plant P"],
    "Technology": ["Solar", "Wind", "Hydropower", "Solar", "Geothermal"],
    "Capacity (MW)": [150, 300, 200, 50, 100],  # Megawatts
    "Cost (Million $)": [200, 400, 350, 100, 250],  # Project cost
    "Location": ["California", "Texas", "Washington", "Nevada", "Idaho"],
    "Completion Year": [2023, 2024, 2022, 2025, 2023]
}

1] Create a series for renewable sources

In [218]:

# Assuming renewable_sources is a set
renewable_sources = {"solar", "wind", "hydropower", "geothermal"}

# Convert the set to a list
renewable_sources_list = list(renewable_sources)

# Create the Series
r_series = pd.Series(renewable_sources_list)

# Print the Series
print(r_series)


0          wind
1    geothermal
2    hydropower
3         solar
dtype: object


In [219]:
project_df=pd.DataFrame(data)
project_df.head()
print("Project DataFrame:")
print(project_df)

# to get 2 and 3rd row of data
print(project_df.iloc[1:3])

Project DataFrame:
              Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  
0  California             2023  
1       Texas             2024  
2  Washington             2022  
3      Nevada             2025  
4       Idaho             2023  
          Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
1  Wind Turbine X        Wind            300               400       Texas   
2    Hydropower Y  Hydropower            200               350  Washington   

   Completion Year  
1             2024  
2             2022  


In [220]:
project_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Project           5 non-null      object
 1   Technology        5 non-null      object
 2   Capacity (MW)     5 non-null      int64 
 3   Cost (Million $)  5 non-null      int64 
 4   Location          5 non-null      object
 5   Completion Year   5 non-null      int64 
dtypes: int64(3), object(3)
memory usage: 372.0+ bytes


In [221]:
project_df.describe()

Capacity (MW)  Cost (Million $)  Completion Year
count        5.00000          5.000000         5.000000
mean       160.00000        260.000000      2023.400000
std         96.17692        119.373364         1.140175
min         50.00000        100.000000      2022.000000
25%        100.00000        200.000000      2023.000000
50%        150.00000        250.000000      2023.000000
75%        200.00000        350.000000      2024.000000
max        300.00000        400.000000      2025.000000

In [222]:
# filter whose capacity  more than 100 mb
filtered_df = project_df[project_df["Capacity (MW)"] > 100]
print(filtered_df)

          Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
0    Solar Farm A       Solar            150               200  California   
1  Wind Turbine X        Wind            300               400       Texas   
2    Hydropower Y  Hydropower            200               350  Washington   

   Completion Year  
0             2023  
1             2024  
2             2022  


In [223]:
#add new column[cost per megawatt]
project_df['Cost per MW'] = project_df['Cost (Million $)'] / project_df['Capacity (MW)']
project_df


Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  Cost per MW  
0  California             2023     1.333333  
1       Texas             2024     1.333333  
2  Washington             2022     1.750000  
3      Nevada             2025     2.000000  
4       Idaho             2023     2.500000

##  Grouping Data

In [225]:
grouped_data = project_df.groupby("Technology")["Capacity (MW)"].sum()
print(grouped_data)

Technology
Geothermal    100
Hydropower    200
Solar         200
Wind          300
Name: Capacity (MW), dtype: int64


# Numpy

In [227]:
import numpy as np

In [228]:
#create numpy aaray
# 1d
arr = np.array([1,2,3])
print(arr)

#2d
arr2 = np.array([[2,3],[3,4]])
print(arr2)

[1 2 3]
[[2 3]
 [3 4]]


In [229]:
# atrribute on 1d array

a1 = np.array([1,2,3])
print(a1.shape)

print(a1.itemsize)

print(a1.ndim)

(3,)
4
1


In [230]:
# on 2 d array
two_D = np.array([[1,2],[3,4]])
print(two_D.shape)
print(two_D.size)
print(two_D.ndim)
print(two_D.dtype)
print(two_D.itemsize)

(2, 2)
4
2
int32
4


In [231]:
# ways of creating numpy array
np.ones(2)

np.zeros(3)

np.random.random(3)

array([0.60822196, 0.20774359, 0.62423048])

In [232]:
#create an array of 3x3 all elemets to be 10
a = np.full((3,3),10)
print(a)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [233]:
#identity matrix
a = np.identity(4)
print(a)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [234]:
# arrange values
a = np.arange(0,10,2)
print(a)

[0 2 4 6 8]


In [235]:
# linspace
la = np.linspace(5,10,3)
print(la)

[ 5.   7.5 10. ]


In [236]:
#print all elements in array

a = np.array([11,22,33,44,55,66])
print(a[:])

print(a[::1])

print(a[::-1])

[11 22 33 44 55 66]
[11 22 33 44 55 66]
[66 55 44 33 22 11]


In [237]:
#string is pallindrome or not 

print("String palindrome or not:")
def is_palindrome(string):
    cleaned_string = ''.join(char.lower() for char in string if char.isalnum())
    
    return cleaned_string == cleaned_string[::-1]
    
user_input = input("Enter a string: ")

if is_palindrome(user_input):
    print(f'"{user_input}" is a palindrome.')
else:
    print(f'"{user_input}" is not a palindrome.')


String palindrome or not:


Enter a string:  anu


"anu" is not a palindrome.


## Array Manipulation

In [319]:
#reshape used to comprise the shape of the image,resize the image,string
a.reshape(2,3)

array([[11, 22, 33],
       [44, 55, 66]])

In [321]:
#transpose the matrix
a = np.array([11,22,33,44,55,66])
print(a.transpose)

<built-in method transpose of numpy.ndarray object at 0x00000237F6CA80F0>


In [323]:
#flatten method

a = np.array([[11,22,33],[44,55,66]])
print(a.flatten('F'))

[11 44 22 55 33 66]


Energy Consumbtion

In [326]:
energy_consumbtion = np.array([12,34,13,24,14])
total = np.sum(energy_consumbtion)
print(total)

97


In [328]:
# Create an array for energy consumption (in kWh)
energy_consumption = np.array([1200, 3400, 2900, 1800, 2500])

# Calculate the mean
mean_consumption = np.mean(energy_consumption)
print("Mean energy consumption (kWh):", mean_consumption)

# Calculate the median
median_consumption = np.median(energy_consumption)
print("Median energy consumption (kWh):", median_consumption)

# Calculate the standard deviation
std_dev_consumption = np.std(energy_consumption)
print("Standard deviation of energy consumption (kWh):", std_dev_consumption)

# Calculate the variance
variance_consumption = np.var(energy_consumption)
print("Variance of energy consumption (kWh):", variance_consumption)

Mean energy consumption (kWh): 2360.0
Median energy consumption (kWh): 2500.0
Standard deviation of energy consumption (kWh): 781.2809993849844
Variance of energy consumption (kWh): 610400.0


In [330]:
#reshape 
import numpy as np

# Original array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Reshape the array into a 3x3 matrix
reshaped_arr = arr.reshape(3, 3)

print("Original Array:")
print(arr)

print("\nReshaped Array (3x3):")
print(reshaped_arr)

Original Array:
[1 2 3 4 5 6 7 8 9]

Reshaped Array (3x3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [332]:
data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150, 250, np.nan]
}

In [334]:
import pandas as pd 
import numpy as np

# Create the DataFrame
data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150, 250, np.nan]
}

df = pd.DataFrame(data)
energy_df=pd.DataFrame(data)

# remove rws with any missing values 
cleaned_df = energy_df.dropna()
print("\nData after removing rows with missing values:")
cleaned_df.head()




Data after removing rows with missing values:


Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
4       Biomass                    2500.0             250.0

In [336]:
#replace missing value with mean
ec_mean = energy_df["Energy Consumption (MWh)"].mean()
print("Mean of energy consumption",ec_mean)

#energy_df["Energy Consumption (MWh)"].fillna(ec_mean,inplace = True)

Mean of energy consumption 2450.0


In [338]:
# forward filling missing values
forward_fill = energy_df.fillna(method="ffill")
print(energy_df)
forward_fill.head()

  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                       NaN             400.0
2    Hydropower                    2900.0               NaN
3    Geothermal                       NaN             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN


C:\Users\hp\AppData\Local\Temp\ipykernel_19216\1192411387.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  forward_fill = energy_df.fillna(method="ffill")


Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    1200.0             400.0
2    Hydropower                    2900.0             400.0
3    Geothermal                    2900.0             150.0
4       Biomass                    2500.0             250.0

In [340]:
# Create a flag column indicating missing values in 'Energy Consumption (MWh)'
energy_df["Missing Consumption"] = energy_df["Energy Consumption (MWh)"].isna().astype(int)
energy_df["Missing Cost"] = energy_df["Cost (Million $)"].isna().astype(int)

print("\nData with Missing Values Flagged:")
energy_df.head()


Data with Missing Values Flagged:


Energy Source  Energy Consumption (MWh)  Cost (Million $)  \
0         Solar                    1200.0             200.0   
1          Wind                       NaN             400.0   
2    Hydropower                    2900.0               NaN   
3    Geothermal                       NaN             150.0   
4       Biomass                    2500.0             250.0   

   Missing Consumption  Missing Cost  
0                    0             0  
1                    1             0  
2                    0             1  
3                    1             0  
4                    0             0

## Data Preprocessing

### 1] MinMaxScaler

In [345]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

energy_df[["Energy Consumption (MWh)","Cost (Million $)"]] = scaler.fit_transform(energy_df[["Energy Consumption (MWh)","Cost (Million $)"]])
print(energy_df)

  Energy Source  Energy Consumption (MWh)  Cost (Million $)  \
0         Solar                      0.00               0.2   
1          Wind                       NaN               1.0   
2    Hydropower                      0.85               NaN   
3    Geothermal                       NaN               0.0   
4       Biomass                      0.65               0.4   
5       Nuclear                      1.00               NaN   

   Missing Consumption  Missing Cost  
0                    0             0  
1                    1             0  
2                    0             1  
3                    1             0  
4                    0             0  
5                    0             1  


### 2] Standardscaler

In [348]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
energy_df[["Energy Consumption (MWh)","Cost (Million $)"]] = scaler.fit_transform(energy_df[["Energy Consumption (MWh)","Cost (Million $)"]])

print(energy_df)

  Energy Source  Energy Consumption (MWh)  Cost (Million $)  \
0         Solar                 -1.637804         -0.534522   
1          Wind                       NaN          1.603567   
2    Hydropower                  0.589610               NaN   
3    Geothermal                       NaN         -1.069045   
4       Biomass                  0.065512          0.000000   
5       Nuclear                  0.982683               NaN   

   Missing Consumption  Missing Cost  
0                    0             0  
1                    1             0  
2                    0             1  
3                    1             0  
4                    0             0  
5                    0             1  


In [350]:
# One-hot encode the 'Energy Source' column
energy_encoded_df = pd.get_dummies(energy_df, columns=["Energy Source"])